// 八股专题数据 — 基于52场面试中220道八股文/基础知识题目整理
// 所有公司名称已模糊化处理

export const baguOverview = {
  title: '大模型算法八股专题',
  subtitle: '52场面试 · 220道八股题 · 按主题分类整理',
  stats: [
    { label: '八股总题数', value: '220', desc: '占总题数13%' },
    { label: '覆盖主题', value: '10+', desc: '大模型全链路知识点' },
    { label: '高频考点', value: '6个', desc: '出现≥4次的核心考点' },
    { label: '考察深度', value: '深', desc: '多数追问到原理/公式层' },
  ],
};

// 按主题分类的八股题目详情
export const baguTopics = [
  {
    id: 'sft',
    area: 'SFT（有监督微调）',
    icon: '🎯',
    color: 'indigo',
    frequency: 5,
    difficultyTag: '中等',
    summary: '几乎每场必涉及，通常在项目追问中引出。重点考察SFT数据构建、训练细节和效果评估。',
    questions: [
      { q: 'SFT的时候有没有碰到什么问题？', freq: 3, difficulty: '中', tag: '训练问题' },
      { q: 'SFT用了多少数据？数据怎么来的？', freq: 4, difficulty: '易', tag: '数据规模' },
      { q: 'SFT的样本是怎么构成的？label是什么？', freq: 3, difficulty: '中', tag: '数据构建' },
      { q: '不做微调和做微调的差异有多大？', freq: 2, difficulty: '中', tag: '消融实验' },
      { q: 'SFT之后准确率到多少？', freq: 3, difficulty: '易', tag: '效果指标' },
      { q: '有没有过拟合的问题？怎么看待？', freq: 2, difficulty: '中', tag: '训练问题' },
      { q: 'PE+SFT组合，precision和recall各提升多少？', freq: 2, difficulty: '中', tag: '效果指标' },
    ],
    keyPoints: [
      'SFT数据的质量比数量更重要',
      '要能说清楚数据构建pipeline：标注→清洗→格式化',
      '消融实验结果要精确到小数点',
      '常见问题：过拟合、数据不平衡、灾难性遗忘',
    ],
  },
  {
    id: 'distill',
    area: '知识蒸馏',
    icon: '💧',
    color: 'sky',
    frequency: 5,
    difficultyTag: '中高',
    summary: '最高频考点之一。R1→小模型的蒸馏链路几乎每场必问，重点考察为什么蒸馏、怎么蒸馏、效果如何。',
    questions: [
      { q: '知识蒸馏具体是怎么设计的？', freq: 4, difficulty: '中', tag: '方案设计' },
      { q: '为什么用大模型蒸馏到小模型？不直接用大模型？', freq: 4, difficulty: '中', tag: '动机' },
      { q: 'R1蒸馏具体怎么做？流程是什么？', freq: 3, difficulty: '中', tag: '技术方案' },
      { q: '为什么选千问3-8B作为基座模型？', freq: 2, difficulty: '中', tag: '模型选择' },
      { q: '32B和8B的效果差异有多大？', freq: 2, difficulty: '中', tag: '效果对比' },
      { q: '蒸馏数据的质量怎么保证？', freq: 3, difficulty: '高', tag: '数据质量' },
      { q: '你们是直接拿蒸馏数据做SFT吗？', freq: 2, difficulty: '易', tag: '训练流程' },
    ],
    keyPoints: [
      '蒸馏动机：延迟、成本、QPS（线上不能用大模型）',
      'DeepSeek R1→千问系列是常见链路',
      '蒸馏数据质量校验：人工抽检 + 自动评估',
      '要能对比不同大小模型的效果差异',
    ],
  },
  {
    id: 'rlhf',
    area: 'RLHF / PPO / GRPO / DAPO',
    icon: '🔄',
    color: 'violet',
    frequency: 4,
    difficultyTag: '高',
    summary: '头部大厂重点考察方向。不仅要知道怎么用，还要能推导为什么——KL散度惩罚、clip、优势函数等理论细节。',
    questions: [
      { q: 'PPO的原理讲一下？KL散度惩罚的作用？', freq: 3, difficulty: '高', tag: '理论推导' },
      { q: 'PPO中clip的作用是什么？', freq: 2, difficulty: '高', tag: '理论推导' },
      { q: 'GRPO和DAPO的核心区别？', freq: 3, difficulty: '高', tag: '算法对比' },
      { q: 'DAPO相比原版GRPO做了哪些改进？', freq: 2, difficulty: '高', tag: '算法改进' },
      { q: 'GRPO效果不好体现在哪里？', freq: 2, difficulty: '中', tag: '效果分析' },
      { q: 'Reward怎么设计的？rule-based还是模型RM？', freq: 3, difficulty: '中', tag: 'Reward设计' },
      { q: '优势函数(Advantage)的作用是什么？', freq: 2, difficulty: '高', tag: '理论推导' },
      { q: '强化学习训练不稳定怎么办？', freq: 2, difficulty: '中', tag: '训练稳定性' },
      { q: '强化学习用的数据和SFT数据一样吗？', freq: 2, difficulty: '易', tag: '数据' },
    ],
    keyPoints: [
      'PPO核心：策略梯度 + KL惩罚 + clip截断',
      'GRPO去掉了value网络，用group内归一化替代',
      'DAPO在GRPO基础上改进：dynamic sampling + token-level loss',
      'Reward设计是开放题，要有自己的思考',
    ],
  },
  {
    id: 'dpo',
    area: 'DPO（直接偏好优化）',
    icon: '⚖️',
    color: 'fuchsia',
    frequency: 3,
    difficultyTag: '中高',
    summary: '中频考点，常与PPO/GRPO对比考察。重点是理解DPO的适用场景和局限性。',
    questions: [
      { q: '为什么DPO在你的场景中效果不好？', freq: 2, difficulty: '中', tag: '场景分析' },
      { q: 'DPO和PPO的区别是什么？', freq: 3, difficulty: '中', tag: '算法对比' },
      { q: '有试过DPO这种对偏好敏感的训练吗？', freq: 2, difficulty: '中', tag: '实践经验' },
      { q: 'DPO对数据质量的敏感性体现在哪？', freq: 1, difficulty: '高', tag: '数据质量' },
    ],
    keyPoints: [
      'DPO将reward隐式融入policy，不需要单独的RM',
      '适合数据质量高、偏好明确的场景',
      '对噪声数据敏感，实际效果可能不如RLHF',
      '要能说清楚为什么某些场景选了GRPO而不是DPO',
    ],
  },
  {
    id: 'quantize',
    area: '模型量化',
    icon: '📐',
    color: 'amber',
    frequency: 4,
    difficultyTag: '高',
    summary: '区分度极高的考点。头部大厂追问到对称/非对称、per-token/per-channel粒度级别，回答"不太了解"会严重扣分。',
    questions: [
      { q: 'AWQ是权重和激活都量化吗？具体原理？', freq: 3, difficulty: '高', tag: '量化方案' },
      { q: '量化是对称还是非对称？区别是什么？', freq: 2, difficulty: '高', tag: '量化理论' },
      { q: 'per-token和per-channel量化的区别？', freq: 2, difficulty: '高', tag: '量化粒度' },
      { q: 'AWQ/GPTQ/SmoothQuant各自原理和区别？', freq: 2, difficulty: '高', tag: '方案对比' },
      { q: '量化用AWQ还是INT8？为什么？', freq: 2, difficulty: '中', tag: '方案选择' },
      { q: '权重量化 vs 激活量化 vs 两者都做？', freq: 1, difficulty: '高', tag: '量化策略' },
      { q: '量化对精度的影响怎么评估？', freq: 2, difficulty: '中', tag: '效果评估' },
    ],
    keyPoints: [
      'AWQ：只量化权重，保护显著权重通道',
      'GPTQ：基于Hessian信息的逐层权重量化',
      'SmoothQuant：平滑激活分布，使激活更容易量化',
      '对称量化：零点固定为0；非对称：零点可偏移',
      'per-channel比per-tensor精度更高，但硬件支持需确认',
    ],
  },
  {
    id: 'vllm',
    area: 'vLLM 推理框架',
    icon: '🚀',
    color: 'emerald',
    frequency: 3,
    difficultyTag: '中高',
    summary: '简历写了vLLM必问。重点考察PagedAttention原理和二次开发经验。',
    questions: [
      { q: 'vLLM版本更新快，你们怎么二次开发的？', freq: 2, difficulty: '中', tag: '工程实践' },
      { q: 'vLLM的核心优化原理是什么？', freq: 2, difficulty: '中', tag: '原理' },
      { q: 'PagedAttention是怎么工作的？', freq: 2, difficulty: '高', tag: '核心原理' },
      { q: 'vLLM你们改了哪些部分？', freq: 3, difficulty: '中', tag: '二次开发' },
      { q: '量化提升QPS做了什么？一次请求多少毫秒？', freq: 2, difficulty: '中', tag: '性能指标' },
    ],
    keyPoints: [
      'PagedAttention：将KV Cache分页管理，减少内存碎片',
      '二次开发：常见改动包括自定义采样策略、batch调度、量化集成',
      '要能给出具体QPS数字和优化前后对比',
      '版本管理：fork + cherry-pick策略',
    ],
  },
  {
    id: 'rag',
    area: 'RAG 检索增强生成',
    icon: '📚',
    color: 'teal',
    frequency: 4,
    difficultyTag: '中高',
    summary: '高频考点，某大厂一面把RAG链路每个环节都追问了一遍。需要有工程深度，不能只停留在demo级别。',
    questions: [
      { q: '用的开源框架吗？还是自研？', freq: 2, difficulty: '易', tag: '技术选型' },
      { q: '多路召回有做吗？语义检索+关键字检索(BM25)？', freq: 3, difficulty: '中', tag: '召回策略' },
      { q: 'Chunk策略是什么？大小、重叠怎么设置？', freq: 3, difficulty: '中', tag: 'Chunk' },
      { q: 'Query改写做了几轮？怎么改写的？', freq: 2, difficulty: '中', tag: 'Query改写' },
      { q: 'Rerank用什么模型？为什么用大模型做rerank？', freq: 3, difficulty: '中', tag: 'Rerank' },
      { q: '非结构化PDF怎么处理？复杂表格/跨页表格？', freq: 2, difficulty: '高', tag: '数据处理' },
      { q: '投票不一致怎么处理？多模型voting怎么设计？', freq: 2, difficulty: '高', tag: '结果聚合' },
      { q: '如果是线上生产RAG系统，你会怎么改方案？', freq: 1, difficulty: '高', tag: '系统设计' },
      { q: 'Embedding模型选的哪个？为什么？', freq: 2, difficulty: '中', tag: '模型选择' },
    ],
    keyPoints: [
      'RAG全链路：解析→切分→向量化→检索→重排→生成',
      '多路召回：语义检索 + BM25关键字检索互补',
      'Chunk策略：512-1024 token，overlap 10-20%',
      'Rerank：cross-encoder > bi-encoder，但延迟更高',
      '生产环境需考虑：缓存、增量更新、监控、fallback',
    ],
  },
  {
    id: 'embedding',
    area: '向量检索与相似度',
    icon: '🧭',
    color: 'cyan',
    frequency: 3,
    difficultyTag: '中高',
    summary: '面试官可能出数学反例。Inner Product和欧式距离的排序可能不一致，要真正理解而非死记。',
    questions: [
      { q: 'Embedding之间用什么相似度度量？', freq: 3, difficulty: '中', tag: '度量方式' },
      { q: 'Inner Product vs Cosine Similarity vs L2 Distance的区别？', freq: 2, difficulty: '高', tag: '数学关系' },
      { q: 'Inner Product和欧式距离排序可能不一致吗？', freq: 1, difficulty: '高', tag: '数学反例' },
      { q: 'ANN近似搜索用的什么算法？HNSW/IVF？', freq: 1, difficulty: '中', tag: '检索算法' },
      { q: 'GME-7B是专做多模态embedding的吗？', freq: 1, difficulty: '易', tag: '模型' },
    ],
    keyPoints: [
      'Cosine Similarity = IP / (||a||·||b||)，归一化后三者等价',
      'IP排序和L2排序不一定一致（向量模长不同时）',
      'HNSW：小世界图，查询快但内存占用大',
      'IVF：倒排索引+聚类，适合大规模场景',
    ],
  },
  {
    id: 'loss',
    area: '损失函数 / 数学基础',
    icon: '📊',
    color: 'rose',
    frequency: 3,
    difficultyTag: '中高',
    summary: '某大厂一面直接要求手写CE loss公式推导。next token prediction的loss计算是基础中的基础。',
    questions: [
      { q: 'Next token prediction的损失函数公式？', freq: 3, difficulty: '高', tag: '公式推导' },
      { q: '词表1万个token，某个词的loss怎么算？', freq: 2, difficulty: '高', tag: '公式推导' },
      { q: 'Cross-Entropy Loss公式推导？', freq: 2, difficulty: '高', tag: '公式推导' },
      { q: 'Softmax + CE的数值稳定性问题？', freq: 1, difficulty: '高', tag: '工程细节' },
      { q: 'Precision和Recall的含义？提高了多少？', freq: 3, difficulty: '易', tag: '评估指标' },
      { q: 'F1 score怎么算？PR曲线怎么画？', freq: 1, difficulty: '中', tag: '评估指标' },
    ],
    keyPoints: [
      'CE Loss = -Σ y_i · log(p_i)，对LLM: L = -log P(x_t | x_{<t})',
      'Softmax数值稳定性：减去max值防溢出',
      'Precision = TP/(TP+FP)，Recall = TP/(TP+FN)',
      '项目中的指标要精确到小数点',
    ],
  },
  {
    id: 'prompt',
    area: 'Prompt Engineering',
    icon: '✏️',
    color: 'orange',
    frequency: 3,
    difficultyTag: '中等',
    summary: '在项目追问中经常涉及。重点是prompt设计的结构化思路和CoT的应用。',
    questions: [
      { q: '提示词怎么设计的？结构是怎样的？', freq: 3, difficulty: '中', tag: '设计方法' },
      { q: 'Prompt组织结构是怎样的？分几个部分？', freq: 2, difficulty: '中', tag: '结构设计' },
      { q: 'CoT（链式思维）在你的场景中怎么用的？', freq: 2, difficulty: '中', tag: 'CoT' },
      { q: 'Few-shot和Zero-shot哪个效果好？差异多大？', freq: 2, difficulty: '中', tag: '对比实验' },
      { q: 'PE（Prompt Engineering）的效果能提升多少？', freq: 2, difficulty: '易', tag: '效果指标' },
    ],
    keyPoints: [
      'Prompt结构：System → Context → Task → Format → Example',
      'CoT对推理任务有显著提升',
      'PE是最低成本的优化手段，优先于微调',
      '要能给出PE前后的具体指标对比',
    ],
  },
  {
    id: 'multimodal',
    area: '多模态',
    icon: '🖼️',
    color: 'pink',
    frequency: 2,
    difficultyTag: '中等',
    summary: '如果简历涉及多模态项目则必问。考察多模态融合方式和具体模型选择。',
    questions: [
      { q: '多模态怎么用的？在哪个环节引入？', freq: 2, difficulty: '中', tag: '方案设计' },
      { q: 'GME-7B做多模态embedding？效果怎么样？', freq: 1, difficulty: '中', tag: '模型选择' },
      { q: '多模态embedding需要微调吗？', freq: 1, difficulty: '中', tag: '训练方式' },
      { q: '图文检索的效果如何评估？', freq: 1, difficulty: '中', tag: '效果评估' },
    ],
    keyPoints: [
      '多模态融合：early fusion vs late fusion',
      'CLIP系列模型用于图文对齐',
      '多模态RAG：图片→描述→文本检索 或 直接多模态检索',
      '评估指标：Recall@K, MRR, NDCG',
    ],
  },
  {
    id: 'coding',
    area: '编程题',
    icon: '💻',
    color: 'slate',
    frequency: 2,
    difficultyTag: '中等',
    summary: '大模型岗编程题出现概率约30%，不算高但不能完全不准备。难度一般为LeetCode中等。',
    questions: [
      { q: 'LRU缓存实现', freq: 1, difficulty: '中', tag: '数据结构' },
      { q: '动态规划题', freq: 1, difficulty: '中', tag: 'DP' },
      { q: '字典/哈希操作相关题', freq: 1, difficulty: '易', tag: '哈希' },
      { q: '时间复杂度分析', freq: 2, difficulty: '易', tag: '复杂度' },
    ],
    keyPoints: [
      'LRU：双向链表 + 哈希表，O(1)读写',
      'DP：明确状态定义和转移方程',
      '面试时先说思路再写代码',
      '大模型岗编程题难度通常不超过LC Medium',
    ],
  },
  {
    id: 'data',
    area: '数据工程',
    icon: '🗂️',
    color: 'lime',
    frequency: 3,
    difficultyTag: '中等',
    summary: '在项目追问中频繁涉及，数据构建和数据质量是大模型工程的基础。',
    questions: [
      { q: '语料构造器是怎样的机制？', freq: 2, difficulty: '中', tag: '数据生成' },
      { q: '用大模型构造数据，质量怎么保证？', freq: 3, difficulty: '中', tag: '质量控制' },
      { q: '多轮对话数据怎么构造？信息保留问题？', freq: 2, difficulty: '中', tag: '多轮数据' },
      { q: '语义相似度+表达距离双维度筛选数据？', freq: 1, difficulty: '高', tag: '数据筛选' },
      { q: '数据不平衡怎么处理？', freq: 2, difficulty: '中', tag: '数据平衡' },
    ],
    keyPoints: [
      '数据质量 > 数据数量，这是业界共识',
      '合成数据需要多维度校验：准确性、多样性、无污染',
      '多轮数据构造：关键信息拆解→分轮插入→上下文保持',
      '数据去重：语义相似度 + 表面形式双重检测',
    ],
  },
];

// 频率分布统计
export const baguFreqDistribution = [
  { name: 'SFT/微调', count: 32, color: '#6366f1' },
  { name: '知识蒸馏', count: 28, color: '#0ea5e9' },
  { name: 'RLHF/PPO/GRPO', count: 26, color: '#8b5cf6' },
  { name: 'RAG检索', count: 24, color: '#14b8a6' },
  { name: '模型量化', count: 22, color: '#f59e0b' },
  { name: 'Prompt设计', count: 18, color: '#f97316' },
  { name: '损失函数/指标', count: 16, color: '#f43f5e' },
  { name: 'vLLM推理', count: 14, color: '#10b981' },
  { name: '向量检索', count: 12, color: '#06b6d4' },
  { name: 'DPO', count: 10, color: '#d946ef' },
  { name: '数据工程', count: 9, color: '#84cc16' },
  { name: '多模态', count: 5, color: '#ec4899' },
  { name: '编程题', count: 4, color: '#64748b' },
];

// 难度分布
export const baguDiffDistribution = [
  { name: '高难度', value: 35, color: '#ef4444', desc: '需要公式推导/原理深入' },
  { name: '中等', value: 55, color: '#f59e0b', desc: '需要理解原理+实践经验' },
  { name: '基础', value: 10, color: '#22c55e', desc: '概念理解即可' },
];

// 八股 vs 项目追问 的关系
export const baguProjectRelation = [
  { type: '纯八股（孤立提问）', percent: 20, desc: '独立的理论/概念题，如"讲讲PPO"' },
  { type: '项目中引出', percent: 65, desc: '从项目细节中自然追问到八股知识点' },
  { type: '系统设计中涉及', percent: 15, desc: '在设计方案时涉及的技术选型' },
];

// 高频易错点
export const baguCommonMistakes = [
  {
    topic: '量化知识',
    mistake: '对"对称vs非对称量化""per-token vs per-channel"回答"不太了解"',
    correct: '对称量化零点固定为0、非对称零点可偏移；per-channel精度更高因为每个通道独立缩放',
    severity: 'high',
  },
  {
    topic: 'AWQ原理',
    mistake: '认为AWQ是"权重和激活都量化"',
    correct: 'AWQ只量化权重，核心思想是找到对激活值影响大的权重通道并保护它们',
    severity: 'high',
  },
  {
    topic: 'PPO理论',
    mistake: '只知道PPO是强化学习算法，说不清KL散度惩罚的具体作用',
    correct: 'KL散度约束新策略不偏离参考策略太远，防止reward hacking和训练不稳定',
    severity: 'high',
  },
  {
    topic: 'DPO vs PPO',
    mistake: '混淆DPO和PPO的适用场景',
    correct: 'DPO将RM隐式编码进policy，适合高质量偏好数据；PPO更灵活但训练更复杂',
    severity: 'medium',
  },
  {
    topic: 'RAG多路召回',
    mistake: '只做了语义检索，忽略关键字检索(BM25)的互补作用',
    correct: '语义检索和关键字检索互补：语义解决同义词，关键字解决精确匹配',
    severity: 'medium',
  },
  {
    topic: 'CE Loss',
    mistake: '手写公式时忘记对数底数或softmax数值稳定性',
    correct: 'CE = -log(softmax(z_t))，softmax前减max值防数值溢出',
    severity: 'medium',
  },
  {
    topic: '项目指标',
    mistake: '说不清楚具体的precision/recall数值',
    correct: '每个阶段的指标要精确到小数点，形成对比表',
    severity: 'medium',
  },
];
